#!/bin/bash

# Bash strict mode
set -euvo pipefail

# Get deps
sudo apt-get -y install curl

# Download intellij and untar/zip it to opt
sudo mkdir -p /opt/intellij-idea
curl -fsSL https://download.jetbrains.com/idea/ideaIU-2017.1.3.tar.gz | sudo tar -xvzC /opt/intellij-idea/ --strip 1

# Copy the logo
sudo cp /opt/intellij-idea/bin/idea.png /usr/share/pixmaps/idea.png

# Symlink idea to path
sudo ln -s /opt/intellij-idea/bin/idea.sh /usr/local/bin/idea

# Create the desktop entry
sudo tee /tmp/idea.desktop << EOF
[Desktop Entry]
Name=IntelliJ IDEA
Type=Application
Exec=idea
Terminal=false
Icon=idea
Comment=Integrated Development Environment
NoDisplay=false
Categories=Development;IDE;
Name[en]=IntelliJ IDEA
EOF

# Install the desktop file
sudo desktop-file-install /tmp/idea.desktop
